# Default Output Name
# This is used if -o is not passed in the CLI. 
# If this is missing, the script defaults to {input_filename}.tif
#output_file: "output_raster.tif"

# Grid Settings
grid:
  # The size of one pixel in the units of the CRS (meters)
  resolution: 0.5
  
  # 'rounded' aligns the grid to integer coordinates, 
  # 'exact' uses the precise min/max of the point cloud.
  bounds_strategy: "exact"

# Processing Settings
processing:
  # Chunk size for reading NetCDF. 
  chunk_size: 5000000 

# Visualization / Bands
# Define what goes into the GeoTIFF channels.
output_bands:
  - variable: "red"
    method: "mean"   # Options: mean, min, max, count
    nodata_val: -9999
  - variable: "green"
    method: "mean"
    nodata_val: -9999
  - variable: "blue"
    method: "mean"
    nodata_val: -9999

# #Example for Elevation Model (Uncomment to use)
# output_bands:
#   - variable: "Z"
#     method: "max" 
#     nodata_val: -9999

# Visualization: Standard False Color (Color Infrared)
# Mapping: NIR -> Red, Red -> Green, Green -> Blue
# output_bands:
#   # --- Band 1 (GeoTIFF Red Channel) ---
#   # Source: Near-Infrared (NIR) ~850nm
#   - variable: "intensity"
#     band_selection: 850.9
#     method: "mean"
#     nodata_val: -9999

#   # --- Band 2 (GeoTIFF Green Channel) ---
#   # Source: Visible Red ~650nm
#   - variable: "intensity"
#     band_selection: 650.1
#     method: "mean"
#     nodata_val: -9999

#   # --- Band 3 (GeoTIFF Blue Channel) ---
#   # Source: Visible Green ~550nm
#   - variable: "intensity"
#     band_selection: 551.3
#     method: "mean"
#     nodata_val: -9999
